# Copyright 2024 Deutsche Telekom IT GmbH
#
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=Test1234!
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  jaeger:
    image: jaegertracing/all-in-one:1
    command:
      - --collector.zipkin.host-port=:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    depends_on:
      elasticsearch:
        condition: service_healthy