// Copyright 2024 Deutsche Telekom IT GmbH
//
// SPDX-License-Identifier: Apache-2.0

pluginManagement {
	repositories {
		mavenCentral()
	}
}

includeBuild('../pubsub-horizon-spring-parent') {
	dependencySubstitution {
		substitute module('de.telekom.eni:horizon-core') using project(':horizon-core')
		substitute module('de.telekom.eni:horizon-spring-boot-autoconfigure') using project(':horizon-spring-boot-autoconfigure')
		substitute module('de.telekom.eni:horizon-spring-boot-starter') using project(':horizon-spring-boot-starter')
	}
}

rootProject.name = 'galaxy'
