# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Gradle Build and Test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Configure init.gradle
        run: |
          cp .github/assets/init.gradle /home/runner/.gradle/init.d

      - name: Execute Gradle build
        id: gradlebuild
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: build-artifacts
          path: build/
          retention-days: 5
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 60
          min-coverage-changed-files: 80
        if: github.event_name == 'pull_request' && steps.gradlebuild.outcome == 'success'